/*
 * SPDX-License-Identifier: LGPL-2.1-or-later
 *
 * Guided remediation: review the generated fixes for the rules that failed,
 * apply the selected ones, then re-scan to verify the outcome.
 */

import React, { useMemo, useRef, useState } from "react";
import { Alert } from "@patternfly/react-core/dist/esm/components/Alert/index.js";
import { Button } from "@patternfly/react-core/dist/esm/components/Button/index.js";
import { Content } from "@patternfly/react-core/dist/esm/components/Content/index.js";
import { ExpandableSection } from "@patternfly/react-core/dist/esm/components/ExpandableSection/index.js";
import { Label } from "@patternfly/react-core/dist/esm/components/Label/index.js";
import { Modal, ModalBody, ModalFooter, ModalHeader } from "@patternfly/react-core/dist/esm/components/Modal/index.js";
import { Progress } from "@patternfly/react-core/dist/esm/components/Progress/index.js";
import { Split, SplitItem } from "@patternfly/react-core/dist/esm/layouts/Split/index.js";
import { Stack, StackItem } from "@patternfly/react-core/dist/esm/layouts/Stack/index.js";
import cockpit from "cockpit";

import { ListingTable } from "cockpit-components-table";
import { useDialogs } from "dialogs";
import { fmt_to_fragments } from "utils";

import { generateFix, remediate, scan } from "../api";
import type { StreamHandle } from "../api";
import { useAsync } from "../app-hooks";
import { downloadFile, errorMessage, ruleShortName, safeFilename, withMember } from "../helpers";
import type {
    FixRuleInfo,
    RemediateProgress,
    RemediateResult,
    ScanProgress,
    ScanResult,
} from "../types";
import { ResultLabel, RiskLabel, ScoreValue, SeverityLabel } from "./labels";
import { ErrorAlert, Loading } from "./states";

const _ = cockpit.gettext;

type Phase = "select" | "applying" | "applied" | "rescanning" | "rescanned" | "error";

function buildScript(result: ScanResult, rules: FixRuleInfo[]): string {
    const lines = [
        "#!/usr/bin/env bash",
        `# Remediation script generated by cockpit-oscap from scan ${result.id}`,
        `# Profile: ${result.profile_title} (${result.profile_id})`,
        "# Review every block before running this script on a system.",
        "",
    ];
    for (const rule of rules) {
        lines.push(`# --- ${rule.id} ---`);
        lines.push(rule.fix_snippet);
        lines.push("");
    }
    return lines.join("\n");
}

export const RemediationDialog = ({ result, initialSelection, onApplied, onRescanned }: {
    result: ScanResult;
    /** Rules to pre-select instead of the default (everything but high-risk fixes). */
    initialSelection?: string[];
    /** Fixes were applied (successfully or not): the remediation history changed. */
    onApplied?: () => void;
    onRescanned?: (rescan: ScanResult) => void;
}) => {
    const Dialogs = useDialogs();
    const fix = useAsync(() => generateFix(result.id), [result.id]);

    const [phase, setPhase] = useState<Phase>("select");
    const [selected, setSelected] = useState<Set<string> | null>(null);
    const [progress, setProgress] = useState<RemediateProgress | null>(null);
    const [outcome, setOutcome] = useState<RemediateResult | null>(null);
    const [scanProgress, setScanProgress] = useState<ScanProgress | null>(null);
    const [rescan, setRescan] = useState<ScanResult | null>(null);
    const [error, setError] = useState<string | null>(null);
    const handle = useRef<StreamHandle<ScanResult> | null>(null);

    const rulesById = useMemo(() => new Map(result.results.map(r => [r.rule_id, r])), [result]);
    const fixable = useMemo(() => (fix.data?.rules ?? []).filter(r => r.has_fix), [fix.data]);
    const unfixable = useMemo(() => (fix.data?.rules ?? []).filter(r => !r.has_fix), [fix.data]);

    // Pre-select the requested rules (the user chose them explicitly, whatever their risk), or
    // everything except high-risk fixes, once the fixes are known
    const requested = useMemo(() => fixable.filter(r => initialSelection?.includes(r.id)), [fixable, initialSelection]);
    const requestedMissing = Boolean(initialSelection?.length) && fix.data !== null && requested.length === 0;
    const selection = useMemo(() => {
        if (selected)
            return selected;
        if (initialSelection)
            return new Set(requested.map(r => r.id));  // empty when the chosen rule has no fix: nothing is applied unasked
        return new Set(fixable.filter(r => r.risk_level !== "high").map(r => r.id));
    }, [selected, fixable, initialSelection, requested]);

    const selectedRules = fixable.filter(r => selection.has(r.id));

    function toggle(ruleId: string, isSelected: boolean) {
        setSelected(withMember(selection, ruleId, isSelected));
    }

    function apply() {
        setPhase("applying");
        setProgress(null);
        setError(null);
        remediate(result.id, selectedRules.map(r => r.id), setProgress).promise
                .then(remediation => {
                    setOutcome(remediation);
                    setPhase("applied");
                    onApplied?.();
                })
                .catch((err: unknown) => {
                    setError(errorMessage(err));
                    setPhase("error");
                });
    }

    function verify() {
        setPhase("rescanning");
        setScanProgress(null);
        // Re-evaluate exactly what was scanned: the bridge reuses the profile, datastream and the
        // tailoring recorded in the original results
        handle.current = scan({ rescanOf: result.id }, setScanProgress);
        handle.current.promise
                .then(scanResult => {
                    setRescan(scanResult);
                    setPhase("rescanned");
                    onRescanned?.(scanResult);
                })
                .catch((err: unknown) => {
                    setError(errorMessage(err));
                    setPhase("error");
                })
                .finally(() => { handle.current = null });
    }

    function close() {
        if (phase === "applying" || phase === "rescanning")
            return;
        Dialogs.close();
    }

    const busy = phase === "applying" || phase === "rescanning";

    let body: React.ReactNode;
    let footer: React.ReactNode;

    if (phase === "select") {
        if (fix.loading) {
            body = <Loading title={_("Generating remediation…")} />;
            footer = <Button variant="link" onClick={close}>{_("Cancel")}</Button>;
        } else if (fix.error) {
            body = <ErrorAlert title={_("Failed to generate remediation")} error={fix.error} onRetry={() => fix.reload()} />;
            footer = <Button variant="link" onClick={close}>{_("Close")}</Button>;
        } else {
            body = (
                <Stack hasGutter>
                    <StackItem>
                        <Alert variant="warning" isInline component="h2" title={_("Remediation changes this system's configuration")}>
                            {requested.length > 0
                                ? _("Review the fix before applying it: fixes that touch authentication, SSH, the firewall, SELinux, mounts or the boot loader are marked high risk. Changes are not undone automatically.")
                                : _("Review each fix before applying it. Fixes that touch authentication, SSH, the firewall, SELinux, mounts or the boot loader are marked high risk and are not selected by default. Changes are not undone automatically.")}
                        </Alert>
                    </StackItem>
                    {requestedMissing && (
                        <StackItem>
                            <Alert variant="info" isInline component="h2" title={_("No fix was generated for the chosen rule")}>
                                {_("OpenSCAP did not produce a Bash fix for it from this scan. The other failed rules with a fix are listed below.")}
                            </Alert>
                        </StackItem>
                    )}
                    {fixable.length > 0 && (
                        <StackItem>
                            <Split hasGutter>
                                <SplitItem isFilled>
                                    <Content component="p">
                                        {cockpit.format(_("$0 of $1 failed rules have an automated fix."),
                                                        fixable.length, fixable.length + unfixable.length)}
                                    </Content>
                                </SplitItem>
                                <SplitItem>
                                    <Button variant="link" isInline onClick={() => setSelected(new Set(fixable.map(r => r.id)))}>
                                        {_("Select all")}
                                    </Button>
                                </SplitItem>
                                <SplitItem>
                                    <Button variant="link" isInline onClick={() => setSelected(new Set())}>
                                        {_("Select none")}
                                    </Button>
                                </SplitItem>
                            </Split>
                        </StackItem>
                    )}
                    <StackItem>
                        <ListingTable
                            id="remediation-rules"
                            aria-label={_("Fixes for failed rules")}
                            variant="compact"
                            columns={[_("Rule"), _("Severity"), _("Risk")]}
                            emptyCaption={_("None of the failed rules has an automated fix")}
                            onSelect={(_ev, isSelected, _rowIndex, rowData) => toggle(String(rowData.props?.id), isSelected)}
                            onHeaderSelect={(_ev, isSelected) =>
                                setSelected(isSelected ? new Set(fixable.map(r => r.id)) : new Set())}
                            rows={fixable.map(rule => {
                                const scanned = rulesById.get(rule.id);
                                return {
                                    props: { key: rule.id, id: rule.id },
                                    selected: selection.has(rule.id),
                                    columns: [
                                        { title: rule.title || scanned?.title || ruleShortName(rule.id), sortKey: rule.title },
                                        { title: <SeverityLabel severity={scanned?.severity ?? "unknown"} /> },
                                        { title: <RiskLabel level={rule.risk_level} reason={rule.risk_reason} /> },
                                    ],
                                    expandedContent: (
                                        <div className="oscap-expanded-details">
                                            {rule.risk_reason && <Content component="p">{rule.risk_reason}</Content>}
                                            <pre className="oscap-code">{rule.fix_snippet}</pre>
                                        </div>
                                    ),
                                };
                            })}
                        />
                    </StackItem>
                    {unfixable.length > 0 && (
                        <StackItem>
                            <ExpandableSection
                                toggleText={cockpit.format(
                                    cockpit.ngettext("$0 failed rule has no automated fix", "$0 failed rules have no automated fix",
                                                     unfixable.length), unfixable.length)}
                            >
                                <ul>
                                    {unfixable.map(rule => (
                                        <li key={rule.id}>{rule.title || rulesById.get(rule.id)?.title || rule.id}</li>
                                    ))}
                                </ul>
                            </ExpandableSection>
                        </StackItem>
                    )}
                </Stack>
            );
            footer = (
                <>
                    <Button id="remediation-apply" variant="primary" onClick={apply} isDisabled={selectedRules.length === 0}>
                        {cockpit.format(cockpit.ngettext("Apply $0 fix", "Apply $0 fixes", selectedRules.length),
                                        selectedRules.length)}
                    </Button>
                    <Button
                        variant="secondary"
                        isDisabled={selectedRules.length === 0}
                        onClick={() => downloadFile(`remediation-${safeFilename(result.id)}.sh`,
                                                    buildScript(result, selectedRules), "text/x-shellscript")}
                    >
                        {_("Download script")}
                    </Button>
                    <Button variant="link" onClick={close}>{_("Cancel")}</Button>
                </>
            );
        }
    } else if (phase === "applying") {
        const total = progress?.total ?? selectedRules.length;
        const current = progress?.current ?? 0;
        body = (
            <Progress
                value={total ? Math.round((Math.max(current - 1, 0)) / total * 100) : 0}
                title={progress
                    ? cockpit.format(_("Applying fix $0 of $1: $2"), current, total, ruleShortName(progress.rule_id))
                    : _("Preparing…")}
                measureLocation="outside"
            />
        );
        footer = <Content component="small">{_("Please keep this page open until remediation finishes.")}</Content>;
    } else if (phase === "applied" && outcome) {
        const applied = outcome.rules.filter(r => r.success).length;
        body = (
            <Stack hasGutter>
                <StackItem>
                    <Alert
component="h2"
                        variant={outcome.success ? "success" : "warning"}
                        isInline
                        title={cockpit.format(_("$0 of $1 fixes applied"), applied, outcome.rules.length)}
                    >
                        {_("Re-scan the system to verify which rules now pass.")}
                    </Alert>
                </StackItem>
                <StackItem>
                    <ListingTable
                        aria-label={_("Remediation outcome")}
                        variant="compact"
                        columns={[_("Rule"), _("Outcome")]}
                        rows={outcome.rules.map(rule => ({
                            props: { key: rule.rule_id },
                            columns: [
                                rulesById.get(rule.rule_id)?.title ?? ruleShortName(rule.rule_id),
                                rule.success
                                    ? <Label status="success" isCompact>{_("Applied")}</Label>
                                    : (
                                        <Label status="danger" isCompact>
                                            {cockpit.format(_("Failed (exit status $0)"), rule.exit_status)}
                                        </Label>
                                    ),
                            ],
                            expandedContent: (rule.output || rule.errors)
                                ? (
                                    <div className="oscap-expanded-details">
                                        {rule.output && <pre className="oscap-code">{rule.output}</pre>}
                                        {rule.errors && <pre className="oscap-code">{rule.errors}</pre>}
                                    </div>
                                )
                                : undefined,
                        }))}
                    />
                </StackItem>
            </Stack>
        );
        footer = (
            <>
                <Button id="remediation-verify" variant="primary" onClick={verify}>{_("Re-scan to verify")}</Button>
                <Button variant="link" onClick={close}>{_("Close")}</Button>
            </>
        );
    } else if (phase === "rescanning") {
        body = (
            <Progress
                value={scanProgress?.progress ?? 0}
                title={scanProgress
                    ? cockpit.format(_("Evaluating rule $0 of $1"), scanProgress.current, scanProgress.total)
                    : _("Starting scan…")}
                measureLocation="outside"
            />
        );
        footer = <Button variant="secondary" onClick={() => handle.current?.cancel()}>{_("Cancel scan")}</Button>;
    } else if (phase === "rescanned" && rescan) {
        const attempted = selectedRules.map(r => r.id);
        const after = new Map(rescan.results.map(r => [r.rule_id, r.result]));
        const fixed = attempted.filter(id => after.get(id) === "pass");
        const remaining = attempted.filter(id => after.get(id) !== "pass");
        body = (
            <Stack hasGutter>
                <StackItem>
                    <Alert
component="h2"
variant={remaining.length === 0 ? "success" : "warning"} isInline
                           title={cockpit.format(_("$0 of $1 remediated rules now pass"), fixed.length, attempted.length)}
                    >
                        <span className="oscap-inline-list" style={{ gap: "var(--pf-t--global--spacer--md)" }}>
                            <span>{_("New score")}</span>
                            <ScoreValue score={rescan.score} size="md" />
                            <span className="oscap-muted">
                                {fmt_to_fragments(_("(was $0)"), <ScoreValue score={result.score} size="md" />)}
                            </span>
                        </span>
                    </Alert>
                </StackItem>
                <StackItem>
                    <ListingTable
                        aria-label={_("Verification outcome")}
                        variant="compact"
                        columns={[_("Rule"), _("Before"), _("After")]}
                        rows={attempted.map(id => ({
                            props: { key: id },
                            columns: [
                                rulesById.get(id)?.title ?? ruleShortName(id),
                                <ResultLabel key="before" result="fail" />,
                                <ResultLabel key="after" result={after.get(id) ?? "unknown"} />,
                            ],
                        }))}
                    />
                </StackItem>
            </Stack>
        );
        footer = (
            <>
                <Button variant="primary" onClick={() => { Dialogs.close(); cockpit.location.go(["results", rescan.id]) }}>
                    {_("View new results")}
                </Button>
                <Button variant="link" onClick={close}>{_("Close")}</Button>
            </>
        );
    } else {
        body = <ErrorAlert title={_("Remediation failed")} error={error} />;
        footer = <Button variant="link" onClick={close}>{_("Close")}</Button>;
    }

    return (
        <Modal id="remediation-dialog" isOpen variant="large" position="top" {...!busy && { onClose: close }}>
            <ModalHeader
                title={_("Remediate failed rules")}
                description={cockpit.format(_("Scan of $0"), result.profile_title)}
            />
            <ModalBody>{body}</ModalBody>
            <ModalFooter>{footer}</ModalFooter>
        </Modal>
    );
};
